#!/bin/bash
# 数据准备示例脚本
# 演示如何使用数据准备工具链

echo "=========================================="
echo "PA-HCL 数据准备工具 - 使用示例"
echo "=========================================="
echo ""

# 设置颜色
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}示例 1: 准备 CirCor 数据集${NC}"
echo "----------------------------------------"
echo "# 步骤 1: 下载数据集"
echo "python download_datasets.py --dataset circor --output-dir ./data/downloads"
echo ""
echo "# 步骤 2: 准备数据（转换为受试者格式）"
echo "python prepare_circor.py \\"
echo "    --input-dir ./data/downloads/extracted/the-circor-digiscope-phonocardiogram-dataset-1.0.3 \\"
echo "    --output-dir ./data/raw/circor \\"
echo "    --verbose"
echo ""
echo "# 步骤 3: 预处理（切分心动周期）"
echo "cd ../.."
echo "python scripts/preprocess.py --raw_dir data/raw/circor --output_dir data/processed"
echo ""
echo "# 或使用快速启动脚本一键完成："
echo -e "${GREEN}./quickstart.sh full circor${NC}"
echo ""
echo ""

echo -e "${BLUE}示例 2: 准备 PhysioNet 2016 数据集${NC}"
echo "----------------------------------------"
echo "# 快速启动："
echo -e "${GREEN}./quickstart.sh full physionet2016${NC}"
echo ""
echo "# 或分步执行："
echo "./quickstart.sh download physionet2016"
echo "./quickstart.sh prepare physionet2016"
echo "./quickstart.sh preprocess physionet2016"
echo ""
echo ""

echo -e "${BLUE}示例 3: 准备自建数据集${NC}"
echo "----------------------------------------"
echo "# 确保数据组织为以下结构："
echo "data/raw/"
echo "├── Normal/"
echo "│   ├── normal_case0001_male_6_20s_USA_A.wav"
echo "│   └── ..."
echo "└── Abnormal/"
echo "    ├── asd_case0001_female_4_20s_USA_A.wav"
echo "    └── ..."
echo ""
echo "# 运行准备脚本："
echo "python prepare_custom.py \\"
echo "    --input-dir ./data/raw \\"
echo "    --output-dir ./data/raw/custom_organized \\"
echo "    --verbose"
echo ""
echo "# 或使用快速启动脚本："
echo -e "${GREEN}./quickstart.sh prepare custom${NC}"
echo -e "${GREEN}./quickstart.sh preprocess custom${NC}"
echo ""
echo ""

echo -e "${BLUE}示例 4: 批量准备所有数据集${NC}"
echo "----------------------------------------"
echo "# 下载所有公开数据集"
echo "python download_datasets.py --dataset all --output-dir ./data/downloads"
echo ""
echo "# 逐个准备"
echo "for dataset in circor physionet2016 pascal; do"
echo "    ./quickstart.sh prepare \$dataset"
echo "done"
echo ""
echo "# 逐个预处理"
echo "for dataset in circor physionet2016 pascal; do"
echo "    ./quickstart.sh preprocess \$dataset"
echo "done"
echo ""
echo ""

echo -e "${BLUE}常用命令速查${NC}"
echo "----------------------------------------"
echo -e "${YELLOW}# 检查环境${NC}"
echo "./quickstart.sh check"
echo ""
echo -e "${YELLOW}# 查看帮助${NC}"
echo "./quickstart.sh help"
echo "python prepare_circor.py --help"
echo ""
echo -e "${YELLOW}# 验证结果${NC}"
echo "tree -L 2 data/raw/circor"
echo "ls -1d data/raw/circor/subject_* | wc -l"
echo "find data/raw/circor -name '*.wav' | wc -l"
echo ""
echo -e "${YELLOW}# 运行测试${NC}"
echo "python test_data_preparation.py -v"
echo ""
echo ""

echo -e "${GREEN}=========================================="
echo "更多详细信息请参考："
echo "  - QUICKSTART.md (快速开始)"
echo "  - README.md (详细文档)"
echo "  - SUMMARY.md (功能总结)"
echo "==========================================${NC}"
